@extends('app')

@section('content')
  <div
    class="
      w-[500px]
      h-auto
      pt-6
      mx-auto
      grid
      grid-cols-1
      gap-6
    "
  >
    <form
      class="
        w-full
        h-full
        grid
        grid-cols-1
        gap-4
        rounded-2xl
        border-white
        border-2
        p-4
        bg-[#1a1d24]
      "
      action="{{ route('categories.store') }}"
      method="POST"
    >
      @csrf

      @if (session('success'))
        <span
          class="
            rounded-full
            w-full
            h-auto
            bg-green-600
            flex
            items-center
            px-5
            py-2
          "
        >
          {{ session('success') }}
        </span>
      @endif

      @error('title')
        <span
          class="
            rounded-full
            w-full
            h-auto
            bg-red-600
            flex
            items-center
            px-5
            py-2
          "
        >
          {{ $message }}
        </span>
        
      @enderror
      <label
        class="
          grid
          grid-cols-1
          grid-rows-2
        "
      >
        <span
          class="
            flex
            items-center
            pl-1
          "
        >
          Nombre de la categoria:
        </span>
        <input
          class="
            placeholder:italic
            placeholder:text-slate-400
            block
            bg-white
            w-full
            border
            border-slate-300
            rounded-full
            py-2
            pl-3
            text-black
            shadow-sm
            focus:outline-none
            focus:border-sky-500
            focus:ring-sky-500
            focus:ring-1
            sm:text-sm
          "
          placeholder="Categoria"
          type="text"
          name="name"
        />
      </label>
      <label
        class="
          grid
          grid-cols-1
          grid-rows-2
        "
      >
        <span
          class="
            flex
            items-center
            pl-1
          "
        >
          Color:
        </span>
        <input
          class="
            placeholder:italic
            placeholder:text-slate-400
            block
            bg-white
            w-full
            border
            border-slate-300
            rounded-full
            py-[.5px]
            px-3
            text-black
            shadow-sm
            focus:outline-none
            focus:border-sky-500
            focus:ring-sky-500
            focus:ring-1
            sm:text-sm
          "
          placeholder="color"
          type="color"
          name="color"
        />
      </label>
      <div
        class="
          flex
          items-center
          justify-center
        "
      >
        <button
          class="
            rounded-full
            p-1
            px-6
            bg-cyan-500
          "
        >
          Crear
        </button>
      </div>
    </form>

    <div
      class="
        w-full
        h-full
        grid
        grid-cols-1
        gap-1
        rounded-2xl
        border-white
        border-2
        p-4
        bg-[#1a1d24]
      "
    >
      <div
        class="
          grid
          grid-cols-4
          border-b-2
          pb-2
        "
      >
        <div
          class="
            pl-2
          "
        >
          <span>Id</span>
        </div>
        <div>
          <span>Nombre</span>
        </div>
        <div
          class="
            flex
            justify-center
          "
        >
          <span>Color</span>
        </div>
        <div
          class="
            flex
            justify-center
          "
        >
          <span>Opciones</span>
        </div>
      </div>
      @foreach ($categories as $category)
        <div
          class="
            grid
            grid-cols-4
            pb-1
            hover:bg-[#a3a3a378]
          "
        >          
          <div
            class="
              pl-2
            "
          >
            <span>
              {{ $category->id }}
            </span>
          </div>
          <div>
            <span>
              {{ $category->name }}
            </span>
          </div>
          <div
            class="
              flex
              items-center
              justify-center
            "
          >
            <div
              class="
                w-[20px]
                h-[20px]
                rounded-full
              "
              style="
                background-color:{{ $category->color }}
              "
            >
            </div>
          </div>
          <div
            class="
              flex
              justify-center
            "
          >
            <a
              href="{{ route('categories.show', ['category' => $category->id]) }}"
              class="
                cursor-pointer
                text-blue-400
              "
            >
              editar
            </a>
            <span
              class="
                mx-2
              "
            >
              |
            </span>
            <form
              action="{{ route('categories.destroy', [$category->id]) }}"
              class="
                cursor-pointer
                text-blue-400
              "
              method="POST"
            >
              @method('DELETE')
              @csrf
              <button>
                eliminar
              </button>
            </form>
          </div>
        </div>
      @endforeach
    </div>
  </div>
@endsection